import { createStyles } from '../theme/createStyles';

export const getSocialStyles = (isDark) => {
  const t = createStyles(isDark);
  return {
    popup: {
      position: 'absolute',
      top: 'calc(100% + 10px)',
      right: 0,
      width: 300,
      background: t.cardBg,
      border: `1px solid ${t.cardBorder}`,
      borderRadius: 16,
      boxShadow: t.popupShadow,
      zIndex: 100,
      overflow: 'hidden',
      maxHeight: '80vh',
      display: 'flex',
      flexDirection: 'column',
    },
    tabs: {
      display: 'flex',
      alignItems: 'center',
      gap: 4,
      padding: '10px 14px',
      borderBottom: `1px solid ${t.cardBorder}`,
    },
    tabBtn: {
      background: 'transparent',
      border: 'none',
      cursor: 'pointer',
      padding: '6px 8px',
      borderRadius: 8,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'background 0.15s',
    },
    tabActive: {
      background: isDark ? 'rgba(255,91,46,0.12)' : 'rgba(255,132,48,0.12)',
    },
    myAvatar: {
      marginLeft: 'auto',
      width: 30,
      height: 30,
      borderRadius: '50%',
      background: t.primaryGradient,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    body: {
      padding: '12px 14px',
      overflowY: 'auto',
      flex: 1,
    },
    title: {
      fontFamily: t.fontPrimary,
      fontSize: 18,
      fontWeight: 800,
      color: t.textPrimary,
      margin: '0 0 10px 0',
    },
    addTitle: {
      fontFamily: t.fontPrimary,
      fontSize: 18,
      fontWeight: 800,
      color: t.textPrimary,
      margin: '0 0 10px 0',
    },
    searchWrap: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      background: t.inputBg,
      borderRadius: 10,
      padding: '7px 12px',
      marginBottom: 12,
    },
    searchInput: {
      background: 'none',
      border: 'none',
      outline: 'none',
      fontSize: 12,
      color: t.textSecondary,
      fontFamily: t.fontSecondary,
      width: '100%',
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: 700,
      color: t.textMuted,
      marginBottom: 8,
      display: 'flex',
      justifyContent: 'space-between',
    },
    sectionCount: {
      fontSize: 10,
      color: t.textMuted,
    },
    friendRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '7px 6px',
      borderRadius: 10,
      cursor: 'pointer',
      marginBottom: 2,
      transition: 'background 0.15s',
    },
    friendInfo: { flex: 1, minWidth: 0 },
    friendName: {
      fontSize: 13,
      fontWeight: 600,
      color: t.textPrimary,
      fontFamily: t.fontSecondary,
    },
    friendStatus: {
      fontSize: 10,
      color: t.textSecondary,
    },

    /* USER CARD */
    userCard: {
      background: isDark ? '#1E1E1E' : '#FFF5F5',
      border: `1px solid ${t.cardBorder}`,
      borderRadius: 16,
      padding: '20px 16px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 8,
      position: 'relative',
      marginBottom: 8,
    },
    cardClose: {
      position: 'absolute',
      top: 10,
      right: 10,
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      padding: 4,
      display: 'flex',
      alignItems: 'center',
    },
    userCardAvatar: {
      width: 70,
      height: 70,
      borderRadius: '50%',
      background: isDark ? '#2a2a2a' : '#f0f0f0',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    userCardName: {
      fontFamily: t.fontPrimary,
      fontSize: 18,
      fontWeight: 800,
      color: t.textPrimary,
    },
    userCardStatus: {
      display: 'flex',
      alignItems: 'center',
    },
    userCardBadge: {
      background: 'rgba(34,197,94,0.15)',
      color: '#22C55E',
      fontSize: 10,
      fontWeight: 700,
      padding: '3px 10px',
      borderRadius: 20,
    },
    sendMsgBtn: {
      background: t.primaryGradient,
      border: 'none',
      borderRadius: 10,
      padding: '10px 20px',
      color: '#fff',
      fontFamily: t.fontSecondary,
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },
    addFriendBtn: {
      background: t.primaryGradient,
      border: 'none',
      borderRadius: 10,
      padding: '10px 20px',
      color: '#fff',
      fontFamily: t.fontSecondary,
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },

    /* CHAT */
    chatListHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    chatListTitle: {
      fontFamily: t.fontPrimary,
      fontSize: 18,
      fontWeight: 800,
      color: t.textPrimary,
    },
    chatRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '8px 6px',
      borderRadius: 10,
      cursor: 'pointer',
      marginBottom: 2,
    },
    chatRowInfo: { flex: 1, minWidth: 0 },
    chatRowName: {
      fontSize: 13,
      fontWeight: 600,
      color: t.textPrimary,
      fontFamily: t.fontSecondary,
    },
    chatRowMsg: {
      fontSize: 11,
      color: t.textSecondary,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    chatRowHora: {
      fontSize: 10,
      color: t.textMuted,
      flexShrink: 0,
    },
    chatHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      paddingBottom: 10,
      borderBottom: `1px solid ${t.cardBorder}`,
      marginBottom: 10,
    },
    backBtn: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      padding: 4,
      display: 'flex',
      alignItems: 'center',
    },
    chatHeaderName: {
      fontSize: 13,
      fontWeight: 700,
      color: t.textPrimary,
    },
    mensajesList: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      overflowY: 'auto',
      maxHeight: 220,
      paddingBottom: 8,
    },
    protocolBadge: {
      fontSize: 8,
      textAlign: 'center',
      color: t.textMuted,
      letterSpacing: '0.05em',
      marginBottom: 4,
    },
    mensajeRecibido: { display: 'flex', justifyContent: 'flex-start' },
    mensajeEnviado: { display: 'flex', justifyContent: 'flex-end' },
    bubbleRecibido: {
      background: t.inputBg,
      borderRadius: '12px 12px 12px 2px',
      padding: '8px 12px',
      fontSize: 11,
      color: t.textPrimary,
      maxWidth: '80%',
      lineHeight: 1.5,
    },
    bubbleEnviado: {
      background: t.primaryGradient,
      borderRadius: '12px 12px 2px 12px',
      padding: '8px 12px',
      fontSize: 11,
      color: '#fff',
      maxWidth: '80%',
      lineHeight: 1.5,
    },
    inputRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      paddingTop: 8,
      borderTop: `1px solid ${t.cardBorder}`,
    },
    chatInput: {
      flex: 1,
      background: t.inputBg,
      border: 'none',
      borderRadius: 10,
      padding: '8px 12px',
      fontSize: 11,
      color: t.textPrimary,
      fontFamily: t.fontSecondary,
      outline: 'none',
    },
    sendBtn: {
      width: 30,
      height: 30,
      borderRadius: '50%',
      background: t.primaryGradient,
      border: 'none',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },

    /* ADD FRIEND */
    addFriendRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '8px 10px',
      borderRadius: 10,
      cursor: 'pointer',
      marginBottom: 4,
      background: t.inputBg,
      border: `1px solid ${t.cardBorder}`,
    },
    overlayCard: {
      position: 'absolute',
      inset: 0,
      background: isDark ? 'rgba(0,0,0,0.75)' : 'rgba(255,255,255,0.75)',
      backdropFilter: 'blur(4px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      zIndex: 10,
      borderRadius: 16,
    },
  };
};
